[package]
name = "xmip-message"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/IlleNilsson/xmip-message"
description = "Immutable Xmip Message model."

[dependencies]
xmip-core = { git = "https://github.com/IlleNilsson/xmip-core", rev = "83f68c482f42a22866902ff7d78e7a3b1d14dcdf" }
xmip-stream = { git = "https://github.com/IlleNilsson/xmip-stream", rev = "3855d6b37988f0ff5962a27662824d5da20cce70" }
xmip-context = { git = "https://github.com/IlleNilsson/xmip-context", rev = "a6220c984c4ec4edffbcc45d578a9a98d0b2242a" }
